[workspace]
authors = ["Peter van Heusden <pvanheusden@uwc.ac.za>"]
channels = ["conda-forge", "bioconda"]
name = "teaching-book"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter-book = ">=2.1.2,<3"
watermark = ">=2.6.0,<3"
jupyterlab = ">=4.5.5,<5"
jupytext = ">=1.19.1,<2"
